### ISSUE TITLE
Plot claim limit in config

### ISSUE THREAD

**Issue by lucasxdavii** [ColinHDev/CPlot#101]
Add claim limit in configuration please

**Comment by Smorted** [comment]
you can set it by permission "cplot.claimPlots.4" or any number u like

**Comment by lucasxdavii** [comment]
> you can set it by permission "cplot.claimPlots.4" or any number u like

I wanted a limit of 2 plots, but I can only get up to 4 limits

**Comment by Smorted** [comment]
oh maybe because the permission "cplot.claimPlots.4" is set to true by default, if you are using pureperms try setting the permission " -cplot.claimPlots.4 " to the player then give him the " cplot.claimPlots.2 " permission, maybe it will work
