### ISSUE TITLE
PM5.10.0 crash

### ISSUE THREAD

**Issue by Atara6431** [ColinHDev/CPlot#105]
In PM5.10.0,Cplot will crash.It's a Minor version updates, update to PM5.10.0 might won't take you too much time, please update so more users will keep useing it. thank you!

Thread: Main
Error: Unhandled async exception: Property "minecraft:vertical_half" is missing
File: plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/SOFe/AwaitGenerator/Await
Line: 587
Type: ColinHDev\CPlot\libs\SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/SOFe/AwaitGenerator/Await(334): ColinHDev\CPlot\libs\SOFe\AwaitGenerator\Await->reject(object pocketmine\data\bedrock\block\BlockStateDeserializeException#172181)
#1 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/SOFe/AwaitGenerator/Await(317): ColinHDev\CPlot\libs\SOFe\AwaitGenerator\Await->wakeup(object Closure#199762)
#2 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/SOFe/AwaitGenerator/Await(552): ColinHDev\CPlot\libs\SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#199762)
#3 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/SOFe/AwaitGenerator/AwaitChild(52): ColinHDev\CPlot\libs\SOFe\AwaitGenerator\Await->recheckPromiseQueue(object ColinHDev\CPlot\libs\SOFe\AwaitGenerator\AwaitChild#116893)
#4 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/base/DataConnectorImpl(197): ColinHDev\CPlot\libs\SOFe\AwaitGenerator\AwaitChild->resolve(array[1])
#5 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/base/DataConnectorImpl(174): ColinHDev\CPlot\libs\poggit\libasynql\base\DataConnectorImpl::ColinHDev\CPlot\libs\poggit\libasynql\base\{closure}(array[1], array[14])
#6 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/base/DataConnectorImpl(181): ColinHDev\CPlot\libs\poggit\libasynql\base\DataConnectorImpl::ColinHDev\CPlot\libs\poggit\libasynql\base\{closure}(object ColinHDev\CPlot\libs\poggit\libasynql\result\SqlSelectResult#117350)
#7 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/base/DataConnectorImpl(239): ColinHDev\CPlot\libs\poggit\libasynql\base\DataConnectorImpl::ColinHDev\CPlot\libs\poggit\libasynql\base\{closure}(array[1])
#8 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/base/SqlThreadPool(116): ColinHDev\CPlot\libs\poggit\libasynql\base\DataConnectorImpl->ColinHDev\CPlot\libs\poggit\libasynql\base\{closure}(array[1])
#9 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/base/DataConnectorImpl(322): ColinHDev\CPlot\libs\poggit\libasynql\base\SqlThreadPool->readResults(array[1], null)
#10 plugins/CPlot_dev-203.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/base/SqlThreadPool(64): ColinHDev\CPlot\libs\poggit\libasynql\base\DataConnectorImpl->checkResults()
#11 pmsrc/src/TimeTrackingSleeperHandler(58): ColinHDev\CPlot\libs\poggit\libasynql\base\SqlThreadPool->ColinHDev\CPlot\libs\poggit\libasynql\base\{closure}()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#13 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#15 pmsrc/src/Server(1690): pocketmine\snooze\SleeperHandler->sleepUntil(float 1705767780.0193)
#16 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor()
#17 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[33] D:\BaiduNetdiskDownload\SeverPM5\, string[41] D:\BaiduNetdiskDownload\SeverPM5\plugins\)
#18 pmsrc/src/PocketMine(364): pocketmine\server()
#19 pmsrc(11): require(string[77] phar://D:/BaiduNetdiskDownload/SeverPM5/PocketMine-MP.phar/src/PocketMine.php)

Code:
[578] 		$this->sleeping = true;
[579] 
[580] 		parent::reject($throwable);
[581] 		foreach($this->catches as $class => $onError){
[582] 			if($class === "" || is_a($throwable, $class)){
[583] 				$onError($throwable);
[584] 				return;
[585] 			}
[586] 		}
[587] 		throw new AwaitException("Unhandled async exception: {$throwable->getMessage()}", 0, $throwable);
[588] 	}
[589] 
[590] 	/**
[591] 	 * @internal This is implementation detail. Existence, signature and behaviour are semver-exempt.
[592] 	 */
[593] 	public function isSleeping() : bool{
[594] 		return $this->sleeping;
[595] 	}
[596] }

**Comment by supercrafter333** [comment]
What git-commit of CPlot do you use?

**Comment by Atara6431** [comment]
what main with git-commit ？sorry I don't understand.I just download the plugin and when I update to PM5.10.0, and then tp to Cplot world, the crash happened. and this report from the crashdumps.

**Comment by Atara6431** [comment]
CPlot_dev-208

**Comment by ColinHDev** [comment]
So, this is fixed?
