### ISSUE TITLE
Help requested: Support of more economy plugins

### ISSUE THREAD

**Issue by ColinHDev** [ColinHDev/CPlot#11]
I am yet not sure what the revamped economy API will look like, but this issue is more about getting requests about economy plugins CPlot should support by default.
Since I can't add every minor economy plugin that was ever made, make sure that the plugin follows the following "rules":
- [ ] The plugin must be open-source. We can't support a closed-source plugin that only a handful of servers use.
- [ ] The plugin must be actively developed, while not having many backwards compatibility breaks in a short amount of time.
  - [ ] If the plugin has an easy to use API that stays the same while catching most of the bc breaks, it may have as many bc breaks as it wants.
- [ ] The plugin should have a decent user base. Although it's not problematic to support small economy plugins, those without a big user base will most likely die sooner than those with such a user base.
- [ ] The plugin can depend on [libasynql](https://github.com/poggit/libasynql), [await-generator](https://github.com/SOF3/await-generator), or anything similar, but it must not.
  - [ ] But if the plugin uses an asynchronous database design, its API should allow us to either provide callable (`onSuccess()`, `onError()`) or handle a `\Generator` function with [await-generator](https://github.com/SOF3/await-generator).

If your plugin does not follow those rules, this shouldn't be a problem. The API will be designed in such a way, that you are able to register your economy plugin to CPlot on startup. This discussion is not about all economy plugins that we support, but more about the collection of economy plugins, we will support by default.

**Comment by supercrafter333** [comment]
Please edit the [Economy Provider Class](https://github.com/ColinHDev/CPlot/blob/development/src/ColinHDev/CPlot/provider/EconomyProvider.php) to make it easier for developers to add new economy plugins.

**Comment by ColinHDev** [comment]
![image](https://user-images.githubusercontent.com/54852588/151234342-20e8c91b-45de-4a81-92e9-9e797abf0455.png)
in the making

**Comment by supercrafter333** [comment]
Gr8!

**Comment by ColinHDev** [comment]
I am currently not sure, how the API should look like because it needs to be possible to register economy plugins with asynchronous and synchronous database designs.
I am favouring the following as approach:
```php
public function getMoney(Player $player, \Closure $onSuccess, ?\Closure $onError) : void {...}
```

**Comment by ColinHDev** [comment]
done with e12f24a2317d68c347277d9b2abee33450c91c16

**Comment by supercrafter333** [comment]
Can you make an example how to use onSuccess and onError for the `getMoney` method?

**Comment by ColinHDev** [comment]
You can see the signature of those callables in the PhpDoc above.
But basically `$onSuccess` accepts either a float (the money) or null (if the player has no account), while `$onError` accepts a `\Throwable`, e.g. if any errors occurred and an exception was thrown.

**Comment by jasonw4331** [comment]
[Capital](https://github.com/SOF3/Capital) and [BedrockEconomy](https://github.com/cooldogedev/BedrockEconomy) are recommended. Capital in particular should be very easy to implement
