### ISSUE TITLE
[BUG]: Async plot events won't be called

### ISSUE THREAD

**Issue by supercrafter333** [ColinHDev/CPlot#112]
I tried to use a async plot event of CPlot in the event listener of my plugin. After I noticed that the `PlotClaimAsyncEvent` wasn't working I tried every other async event of CPlot.
But no async event has been called. I tried to just print a message to the console when a async event is called - didn't work.

#111 don't fix this bug. I think there's something wrong with `libAsynEvent`. I don't really have so much knowledge about await stuff so I'm unable to fix the bug in my PR.

**Comment by supercrafter333** [comment]
I'm using [3366701](https://github.com/ColinHDev/CPlot/commit/3366701150cbb4b0b6ae17beb5139c885fd39570) on a PocketMine-MP 5.18.0 server with PHP 8.2.17.

**Comment by ColinHDev** [comment]
Should be fixed now, the release can be found [here](https://github.com/ColinHDev/CPlot/releases/tag/development-release)
