### ISSUE TITLE
Incompatibility with Minecraft's vanilla player selectors

### ISSUE THREAD

**Issue by jasonw4331** [ColinHDev/CPlot#15]
The Player selectors (`@a`, `@p`, `@r`, etc.) don't work natively with this plugin.
When trying to use another plugin like [PlayerSelectors](https://poggit.pmmp.io/p/PlayerSelectors) as a workaround, it fails due to the command being locked from already running

**Comment by ColinHDev** [comment]
I am not really sure if this is something that should be natively supported. On the other side, I don't think it's easily possible without native support. I made the lock to ensure that no one runs a command while another isn't finished. The idea was to prevent race conditions, although it probably doesn't completely achieve that if I think about it now...
