### ISSUE TITLE
I really want to use your plugin, but it gives me an error

### ISSUE THREAD

**Issue by RodolfoDorfis** [ColinHDev/CPlot#21]
![Capturar](https://user-images.githubusercontent.com/99916320/170800833-96f12fcd-c6bd-4708-8da9-6c76bd8495e2.JPG)
I really wanted to use your plugin but I can't solve this problem.
It always gives this error that I will send you.
help me there please

**Comment by ColinHDev** [comment]
Who build you that `.phar`?

**Comment by supercrafter333** [comment]
Just use the phar-file from poggit or build CPlot using Composer.

**Comment by ColinHDev** [comment]
I am not sure if composer works that well, but you should either use [poggit](https://poggit.pmmp.io/ci/ColinHDev/CPlot/~) or any other plugin-builder which supports virion injection like my [build script](https://github.com/ColinHDev/pmmp-plugin-build-script)
