### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by Gabriel00013D** [ColinHDev/CPlot#28]
[11:21:24.195] [Server thread/CRITICAL]: Error: "Class "poggit\libasynql\libasynql" not found" (EXCEPTION) in "plugins/CPlot-development/src/ColinHDev/CPlot/provider/DataProvider" at line 103
--- Stack trace ---
  #0 pmsrc/src/utils/SingletonTrait(31): ColinHDev\CPlot\provider\DataProvider->__construct()
  #1 pmsrc/src/utils/SingletonTrait(36): ColinHDev\CPlot\provider\DataProvider::make()
  #2 plugins/CPlot-development/src/ColinHDev/CPlot/CPlot(44): ColinHDev\CPlot\provider\DataProvider::getInstance()
  #3 pmsrc/src/plugin/PluginBase(117): ColinHDev\CPlot\CPlot->onEnable()
  #4 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)

**Comment by ColinHDev** [comment]
You can't just download the plugin's source code and run it.
This plugin requires [virions from poggit](https://poggit.github.io/support/virion.html) to run. If those are not injected into the code, you will get errors like those.
Use the phar version of this plugin from [poggit](https://poggit.pmmp.io/ci/ColinHDev/CPlot/~) or build the phar yourself with a build script that supports virions, like [mine](https://github.com/ColinHDev/pmmp-plugin-build-script).
