### ISSUE TITLE
Road Block

### ISSUE THREAD

**Issue by NeturCrafter** [ColinHDev/CPlot#31]
I can't set the road block to Cyan Terracotta because it will be set then to the default value **Oak Planks** ingame

This what I did:
**roadBlock: "Cyan Terracotta"**

**Comment by supercrafter333** [comment]
You should try to use `cyan_terracotta`

**Comment by NeturCrafter** [comment]
Still not working

**Comment by ColinHDev** [comment]
Try `Cyan Glazed Terracotta` or `cyan_glazed_terracotta`

**Comment by NeturCrafter** [comment]
Worked thank you
