### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by galaxytwenty** [ColinHDev/CPlot#36]
is there a PlotRoadSchmematic addon or PlotRoadSchmematic plugin for CPlot ?

**Comment by ColinHDev** [comment]
No
You can find a list of all official addons in the README.md.
What should a `PlotRoadSchematic` even do? The schematic system itself should be finished.

**Comment by galaxytwenty** [comment]
so a Plot Road Schematic can change the road with multiple blocks not only one road block..
Like i build a small piece of road, save them into schematic, and the plugin or the addon loads this piece and repeat it on all roads.

uhhmm maybe i find a example on YT, when yes i paste the link here.

Thanks and greet

**Comment by galaxytwenty** [comment]
https://www.youtube.com/watch?v=0mEltNLntOU

**Comment by ColinHDev** [comment]
This is literally already in the plugin.
It was supported from the beginning when I made this plugin public at the start of the year and was already working two years ago for a server teaser back then:
https://youtu.be/uquTg91s4N4

**Comment by ColinHDev** [comment]
Create a simple template world based on your current world settings with the `/plot schematic generate` command.

Build a road (or plot) which you want to use for your world.

Save it to a schematic file (which you can easily share with others!) with the `/plot schematic save` command.

Add those schematic names into your config file as either `road schematic`, `merge road schematic` or `plot schematic`.

Generate a new plot world.
