### ISSUE TITLE
/p Claim Bug???

### ISSUE THREAD

**Issue by galaxytwenty** [ColinHDev/CPlot#39]
Hey Colin.

When i try to execute /p claim or /p auto then CPlot Gives me the plot hwo i stand.
but when i try to execute /p claim or /p auto (on a diferrent plot) it says me:

plot.subcommandExecuting = "§cPlease wait before running §6{%0}§c. Another command is currently executing (§6{%1}§c)."

so i wait LONG LONG but nothing change
i used dev 119 from poggit.

EDIT: i cant run any subcommand when i have before run a sbcommand!

Console:

Fatal error: Uncaught ErrorException: SQLite3::prepare(): Unable to prepare statement: 1, near "UPDATE": syntax error in phar://C:/Users/####/Desktop/PM4/server/plugins/CPlot_dev-119.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php:79
Stack trace:
#0 [internal function]: pocketmine\errorhandler\ErrorToExceptionHandler::handle(2, 'SQLite3::prepar...', 'phar://C:/Users...', 79)
#1 phar://C:/Users/####/Desktop/M4/server/plugins/CPlot_dev-119.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php(79): SQLite3->prepare('INSERT INTO plo...')
#2 phar://C:/Users/####/Desktop/PM4/server/plugins/CPlot_dev-119.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/base/SqlSlaveThread.php(88): ColinHDev\CPlot\libs\poggit\libasynql\sqlite3\Sqlite3Thread->executeQuery(Object(SQLite3), 2, 'INSERT INTO plo...', Array)
#3 phar://C:/Users/####/Desktop/PM4/server/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(93): ColinHDev\CPlot\libs\poggit\libasynql\base\SqlSlaveThread->onRun()
#4 [internal function]: pocketmine\thread\Thread->run()
#5 {main}
  thrown in phar://C:/Users/####/Desktop/PM4/server/plugins/CPlot_dev-119.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 79

Thanks in Advance
Greeetz GLX20

**Comment by ColinHDev** [comment]
That should not happen... But I am using SQLite myself on my test server, so I don't understand why you get an error here.
Is that everything that gets pasted to the console?

```
When i try to execute /p claim or /p auto then CPlot Gives me the plot hwo i stand.
but when i try to execute /p claim or /p auto (on a diferrent plot) it says me:
```
Could you please explain more precisely what you did?

**Comment by PTKDrake** [comment]
I got the same error, seems to be the problem with sqlite query.

**Comment by PTKDrake** [comment]
[cplot.set.plotPlayer](https://github.com/ColinHDev/CPlot/blob/development/resources/sql/sqlite.sql#L324)
