### ISSUE TITLE
[FR]: Please add custom events

### ISSUE THREAD

**Issue by supercrafter333** [ColinHDev/CPlot#4]
Can you please add custom events like:CPlotLeaveEvent, Enter, Block (Place, Break, Interact), Telelport and some more (like MyPlot have it)?

Custom events are very important for outstanding plugin-developers.

Thank you :)

**Comment by ColinHDev** [comment]
As this plugin originally wasn't intended to be open-source, I never bothered to add events, since I would be mostly the only one contributing to this.
But if there is demand, I don't think this causes any harm.
```
- PlotEnterEvent, PlotLeaveEvent
- PlotBlockPlace, PlotBlockBreak, PlotBlockInteract (Are those really necessary? Couldn't you just use the ones provided by PMMP?)
- PlotTeleportEvent (We should come up with a better name.)
(more ideas welcomed)
```

**Comment by supercrafter333** [comment]
Yes. Custom events are realy cool for outstanding developers. The listed events in your message are actually enough to personalize enough.

**Comment by ColinHDev** [comment]
This will be addressed soon, probably with the help of [libAsyncEvent](https://github.com/ColinHDev/libAsyncEvent).
