### ISSUE TITLE
New Ideas

### ISSUE THREAD

**Issue by GamerMJay** [ColinHDev/CPlot#40]
Hello, can you add /p setowner and /p middle?

**Comment by GamerMJay** [comment]
and /p kick?

**Comment by ColinHDev** [comment]
`/plot kick` got implemented with 9821a3e9012e81c4381cea3def01179e12534860

**Comment by GamerMJay** [comment]
Nice

**Comment by ColinHDev** [comment]
`/plot middle` got implemented with a0ba95c889bc972be475440380fdf585116a977b

**Comment by ColinHDev** [comment]
`/p kick` and `/p middle` got already implemented.
`/p setowner` is already discussed in more detail at #45, so I'm gonna close this issue
