### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NeturCrafter** [ColinHDev/CPlot#55]
Ich kann auf einem 4er merge nicht in der Mitte des Merges was abbauen/bauen

**Comment by ColinHDev** [comment]
I will look into this tomorrow.

Please write future issues and comments in English so other people not familiar with the German language can understand you as well.

**Comment by ColinHDev** [comment]
Sorry, I am not able to reproduce this. Please make sure, you use the latest version of the plugin.
