### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by NeturCrafter** [ColinHDev/CPlot#57]
Add /p dispose <player> Command

**Comment by ghost** [comment]
Use /p reset

**Comment by ColinHDev** [comment]
I don't think that's what he means.
@NetureCrafter, could you please explain what you want your command to do?

**Comment by NeturCrafter** [comment]
The command should give the plot to another player

**Comment by ColinHDev** [comment]
This got already suggested here: https://github.com/ColinHDev/CPlot/issues/45
