### ISSUE TITLE
[Bug] Error on start

### ISSUE THREAD

**Issue by Bubbelwubbel** [ColinHDev/CPlot#6]
Ehm, idk. my english is bad. German? xd

![image](https://user-images.githubusercontent.com/65186341/149575200-c50fee87-6b31-471a-85cd-58302bb2a47c.png)

**Comment by ColinHDev** [comment]
Please provide the whole crashdump as a text, not an image. It's easier to read on mobile.
(Bitte sende den ganzen Crashdump als Text, nicht als Bild. So ist es leichter am Handy zu lesen.)

**Comment by Bubbelwubbel** [comment]
Okay, here:
[Fri_Jan_14-21.11.49-CET_2022.log](https://github.com/ColinHDev/CPlot/files/7872949/Fri_Jan_14-21.11.49-CET_2022.log)

**Comment by ColinHDev** [comment]
I fail to understand what's wrong there. But I am currently reworking the whole database part with [libasyql](https://github.com/poggit/libasynql) and [await-generator](https://github.com/SOF3/await-generator), so I don't see the point in further investigating this at the moment.

**Comment by Bubbelwubbel** [comment]
Yes, that's a mystery to me too, and as soon as I use an older version, another error comes up with it. I already delete the folder in plugin_data but idk
(Ja, mir ist das auch ein Rätsel, und sobald ich eine Ältere Version nutze, kommt dann ein andere Fehler mit dem. Ich lösche bereits den Ordner in plugin_data aber idk)
