### ISSUE TITLE
Add PHP 8.1.x support, please

### ISSUE THREAD

**Issue by supercrafter333** [ColinHDev/CPlot#67]
Could you please add support for PHP 8.1.x?

PMMP will bump the PHP version to 8.1 in a few months and CPlot should be ready for testing it with PHP 8.1. At this time CPlot isn't ready and users will get an error on starting the server:
```
PocketMine-MP version: 4.12.1 [Protocol 560]
Git commit: 7ae6425d05cce581854f44c13845635f2ce0eef2
PHP version: 8.1.13
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CPlot

Error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of ColinHDev\CPlot\libs\poggit\libasynql\generic\GenericStatementImpl::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/Test/plugins/CPlot_dev-136.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/generic/GenericStatementImpl.php:233
File: plugins/CPlot_dev-136.phar/src/ColinHDev/CPlot/libs/poggit/libasynql/generic/GenericStatementImpl
Line: 41
Type: E_ERROR
```

**Comment by ColinHDev** [comment]
I agree, but this specific error has something to do with [libasynql](https://github.com/poggit/libasynql).

**Comment by supercrafter333** [comment]
Yes, but this error is since PHP 8.1.

**Comment by jasonw4331** [comment]
https://github.com/poggit/libasynql/issues/87 is already noted on libasynql. It seems there won't be an update from sofe unless someone PRs it

**Comment by supercrafter333** [comment]
I opened a [PR](https://github.com/poggit/libasynql/pull/89). I hope SOF3 will review to it soon. It's just a problem with the JsonSerializable interface that can be fixed by declaring the return-type for the method.

**Comment by supercrafter333** [comment]
PR was merged. @ColinHDev you Just have to make a new commit for updating it on [Poggit-Dev](https://poggit.pmmp.io/dev).

**Comment by ColinHDev** [comment]
As far as I can tell, there seems to be no new release for it.
