### ISSUE TITLE
pm5-branch: Change API to 5.0.0 and keep updating for PM5

### ISSUE THREAD

**Issue by supercrafter333** [ColinHDev/CPlot#68]
Please update the API-tag in the `plugin.yml` to 5.0.0 (actually it's 4.0.0). CPlot PM5 is also using some methods that was removed or renamed in PM5. Please keep updating the branch and maybe switch to PM5 as the main-api-version of CPlot. PM5 will release in under 3 months and CPlot should be ready to test it in PM5.

**Comment by ColinHDev** [comment]
Done in a2d922abb2ea0598a4cb9fbd33438e89b5e20ae0
