### ISSUE TITLE
I got this error by claiming a plot. i use mysql as dataprovider

### ISSUE THREAD

**Issue by swnck** [ColinHDev/CPlot#71]
![image](https://user-images.githubusercontent.com/83925560/221658667-e4fcfded-ede1-4526-a50b-a9118566d373.png)

on this line:

![image](https://user-images.githubusercontent.com/83925560/221658725-a3fc1125-0684-435a-a28d-790a45a7f08a.png)

**Comment by ColinHDev** [comment]
Fixed as of 5935103dfaef019b2275167c1c90c3ef814cb204
