### ISSUE TITLE
MyPlot compatiblity fails if AllowFireTicking is not set in the world config.yml

### ISSUE THREAD

**Issue by HimbeersaftLP** [ColinHDev/CPlot#76]
Old configurations of MyPlot don't have this value: https://github.com/ColinHDev/CPlot/blob/a677069f425065f63a555f0afe22c17c4f183c6e/src/ColinHDev/CPlot/provider/DataProvider.php#L1515

Causing the following error:
```txt
ErrorException: "Undefined array key "AllowFireTicking"" (EXCEPTION) in "plugins/pharynx-output.phar/src/ColinHDev/CPlot/provider/DataProvider" at line 1515
```

**Comment by ColinHDev** [comment]
Thank you really much for your reports.
You don't happen to know how MyPlot behaved in that version, to decide the flag's value?

**Comment by HimbeersaftLP** [comment]
Looks like the default is false: https://github.com/jasonw4331/MyPlot/blob/cc5b2f81817166c89bd62a5761daaf9f480ececf/src/MyPlot/EventListener.php#L71

**Comment by HimbeersaftLP** [comment]
Thank you!
