### ISSUE TITLE
Crash on Startup... 

### ISSUE THREAD

**Issue by note3crafter** [ColinHDev/CPlot#78]
PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.2.6
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN

Error: Unhandled async exception: zlib_decode(): data error
File: /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await
Line: 587
Type: SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(334): SOFe\AwaitGenerator\Await->reject(object ErrorException#59770)
#1 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(317): SOFe\AwaitGenerator\Await->wakeup(object Closure#186332)
#2 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(552): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#186332)
#3 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#159822)
#4 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(197): SOFe\AwaitGenerator\AwaitChild->resolve(array[1])
#5 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(174): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1], array[14])
#6 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(181): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(object poggit\libasynql\result\SqlSelectResult#185746)
#7 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(239): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1])
#8 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/SqlThreadPool(111): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
#9 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[6])
#10 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/SqlThreadPool(64): poggit\libasynql\base\DataConnectorImpl->checkResults()
#11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): poggit\libasynql\base\SqlThreadPool->poggit\libasynql\base\{closure}()
#12 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#14 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686508724.8643)
#15 (): [38;5;227m--- below is the original stack trace ---(B[m()
#16 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(223): poggit\libasynql\base\DataConnectorImpl->executeImplRaw(array[1], array[1], array[1], object Closure#159844, object Closure#159821)
#17 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(180): poggit\libasynql\base\DataConnectorImpl->executeImpl(string[15] cplot.get.world, array[1], int 3, object Closure#159844, object Closure#159821)
#18 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(172): poggit\libasynql\base\DataConnectorImpl->executeImplLast(string[15] cplot.get.world, array[1], int 3, object Closure#159843, object Closure#159821)
#19 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(196): poggit\libasynql\base\DataConnectorImpl->executeSelect(string[15] cplot.get.world, array[1], object Closure#159845, object Closure#159821)
#20 plugins/CPlot-development/src/ColinHDev/CPlot/provider/DataProvider(625): poggit\libasynql\base\DataConnectorImpl->asyncSelect(string[15] cplot.get.world, array[1])
#21 (): ColinHDev\CPlot\provider\DataProvider->awaitWorld(string[9] CityBuild)
#22 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(376): Generator->send(object Closure#159821)
#23 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(332): SOFe\AwaitGenerator\Await->SOFe\AwaitGenerator\{closure}()
#24 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(129): SOFe\AwaitGenerator\Await->wakeup(object Closure#159841)
#25 plugins/CPlot-development/src/ColinHDev/CPlot/provider/DataProvider(607): SOFe\AwaitGenerator\Await::g2c(object Generator#159834)
#26 plugins/CPlot-development/src/ColinHDev/CPlot/tasks/EntityMovementTask(39): ColinHDev\CPlot\provider\DataProvider->loadWorldIntoCache(string[9] CityBuild)
#27 pmsrc/src/scheduler/TaskHandler(113): ColinHDev\CPlot\tasks\EntityMovementTask->onRun()
#28 pmsrc/src/scheduler/TaskScheduler(137): pocketmine\scheduler\TaskHandler->run()
#29 pmsrc/src/plugin/PluginManager(530): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 2)
#30 pmsrc/src/Server(1782): pocketmine\plugin\PluginManager->tickSchedulers(int 2)
#31 pmsrc/src/Server(1671): pocketmine\Server->tick()
#32 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#33 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[12] /home/CCPM5/, string[20] /home/CCPM5/plugins/)
#34 pmsrc/src/PocketMine(357): pocketmine\server()
#35 pmsrc(11): require(string[56] phar:///home/CCPM5/PocketMine-MP.phar/src/PocketMine.php)

Code:
[578] 		$this->sleeping = true;
[579] 
[580] 		parent::reject($throwable);
[581] 		foreach($this->catches as $class => $onError){
[582] 			if($class === "" || is_a($throwable, $class)){
[583] 				$onError($throwable);
[584] 				return;
[585] 			}
[586] 		}
[587] 		throw new AwaitException("Unhandled async exception: {$throwable->getMessage()}", 0, $throwable);
[588] 	}
[589] 
[590] 	/**
[591] 	 * @internal This is implementation detail. Existence, signature and behaviour are semver-exempt.
[592] 	 */
[593] 	public function isSleeping() : bool{
[594] 		return $this->sleeping;
[595] 	}
[596] }
--- Previous ---
ErrorException: "zlib_decode(): data error" (EXCEPTION) in "plugins/CPlot-development/src/ColinHDev/CPlot/utils/ParseUtils" at line 91
  #0 (): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[25] zlib_decode(): data error, string[78] /home/CCPM5/plugins/CPlot-development/src/ColinHDev/CPlot/utils/ParseUtils.php, int 91)
  #1 plugins/CPlot-development/src/ColinHDev/CPlot/utils/ParseUtils(91): zlib_decode(string[20] minecraft:planks;5;0)
  #2 plugins/CPlot-development/src/ColinHDev/CPlot/utils/ParseUtils(78): ColinHDev\CPlot\utils\ParseUtils::parseBlockFromCompressedTreeRoot(string[20] minecraft:planks;5;0)
  #3 plugins/CPlot-development/src/ColinHDev/CPlot/utils/ParseUtils(68): ColinHDev\CPlot\utils\ParseUtils::parseBlockFromString(string[20] minecraft:planks;5;0)
  #4 plugins/CPlot-development/src/ColinHDev/CPlot/worlds/WorldSettings(166): ColinHDev\CPlot\utils\ParseUtils::parseBlockFromArray(array[14], string[9] roadBlock)
  #5 plugins/CPlot-development/src/ColinHDev/CPlot/provider/DataProvider(634): ColinHDev\CPlot\worlds\WorldSettings::fromArray(array[14])
  #6 (): ColinHDev\CPlot\provider\DataProvider->awaitWorld(string[9] CityBuild)
  #7 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(553): Generator->send(array[1])
  #8 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(332): SOFe\AwaitGenerator\Await->SOFe\AwaitGenerator\{closure}()
  #9 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(317): SOFe\AwaitGenerator\Await->wakeup(object Closure#186332)
  #10 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/Await(552): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#186332)
  #11 /home/CCPM5/virions/await-generator_dev-127.phar/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#159822)
  #12 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(197): SOFe\AwaitGenerator\AwaitChild->resolve(array[1])
  #13 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(174): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1], array[14])
  #14 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(181): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(object poggit\libasynql\result\SqlSelectResult#185746)
  #15 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(239): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1])
  #16 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/SqlThreadPool(111): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
  #17 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[6])
  #18 /home/CCPM5/virions/libasynql_dev-200.phar/src/poggit/libasynql/base/SqlThreadPool(64): poggit\libasynql\base\DataConnectorImpl->checkResults()
  #19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): poggit\libasynql\base\SqlThreadPool->poggit\libasynql\base\{closure}()
  #20 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #22 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686508724.8643)
  #23 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #24 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[12] /home/CCPM5/, string[20] /home/CCPM5/plugins/)
  #25 pmsrc/src/PocketMine(357): pocketmine\server()
  #26 pmsrc(11): require(string[56] phar:///home/CCPM5/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by note3crafter** [comment]
vielleicht hilft es dir weiter...

**Comment by supercrafter333** [comment]
Virion/Library error

**Comment by note3crafter** [comment]
und wie bekommt man es behoben? bzw was ist da jetzt genau der fehler?

**Comment by supercrafter333** [comment]
Wait until AwaitGenerator was updated and also until CPlot uses the fixed AwaitGenerator version.

You can open an issue at AwaitGenerator.

**Comment by ColinHDev** [comment]
It's not a problem with AwaitGenerator. It's just hidden because of how AwaitGenerator deals with thrown exceptions.
Someone only needs to build this plugin with the correct version of libasnql. That should resolve the error.
But I am working on automated plugin building everytime someone pushes to a branch.

**Comment by ColinHDev** [comment]
<https://github.com/ColinHDev/CPlot/releases/tag/development-release> should work now, so this issue can be closed as correctly built plugin phars for each branch can be found there.
