### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by note3crafter** [ColinHDev/CPlot#79]
PocketMine-MP Crash Dump Tue Jun 13 10:25:59 UTC 2023

PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.2.6
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CPlot

Error: Unhandled async exception: zlib_decode(): data error
File: plugins/CPlot_dev-development.phar/src/_48e62591872a1dc7f793_SOFe/AwaitGenerator/Await
Line: 587
Type: _48e62591872a1dc7f793_SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 plugins/CPlot_dev-development.phar/src/_48e62591872a1dc7f793_SOFe/AwaitGenerator/Await(334): _48e62591872a1dc7f793_SOFe\AwaitGenerator\Await->reject(object ErrorException#149645)
#1 plugins/CPlot_dev-development.phar/src/_48e62591872a1dc7f793_SOFe/AwaitGenerator/Await(317): _48e62591872a1dc7f793_SOFe\AwaitGenerator\Await->wakeup(object Closure#184231)
#2 plugins/CPlot_dev-development.phar/src/_48e62591872a1dc7f793_SOFe/AwaitGenerator/Await(552): _48e62591872a1dc7f793_SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#184231)
#3 plugins/CPlot_dev-development.phar/src/_48e62591872a1dc7f793_SOFe/AwaitGenerator/AwaitChild(52): _48e62591872a1dc7f793_SOFe\AwaitGenerator\Await->recheckPromiseQueue(object _48e62591872a1dc7f793_SOFe\AwaitGenerator\AwaitChild#59776)
#4 plugins/CPlot_dev-development.phar/src/_390328fdf2e8a8c4fad9_poggit/libasynql/base/DataConnectorImpl(197): _48e62591872a1dc7f793_SOFe\AwaitGenerator\AwaitChild->resolve(array[1])
#5 plugins/CPlot_dev-development.phar/src/_390328fdf2e8a8c4fad9_poggit/libasynql/base/DataConnectorImpl(174): _390328fdf2e8a8c4fad9_poggit\libasynql\base\DataConnectorImpl::_390328fdf2e8a8c4fad9_poggit\libasynql\base\{closure}(array[1], array[14])
#6 plugins/CPlot_dev-development.phar/src/_390328fdf2e8a8c4fad9_poggit/libasynql/base/DataConnectorImpl(181): _390328fdf2e8a8c4fad9_poggit\libasynql\base\DataConnectorImpl::_390328fdf2e8a8c4fad9_poggit\libasynql\base\{closure}(object _390328fdf2e8a8c4fad9_poggit\libasynql\result\SqlSelectResult#166714)
#7 plugins/CPlot_dev-development.phar/src/_390328fdf2e8a8c4fad9_poggit/libasynql/base/DataConnectorImpl(239): _390328fdf2e8a8c4fad9_poggit\libasynql\base\DataConnectorImpl::_390328fdf2e8a8c4fad9_poggit\libasynql\base\{closure}(array[1])
#8 plugins/CPlot_dev-development.phar/src/_390328fdf2e8a8c4fad9_poggit/libasynql/base/SqlThreadPool(111): _390328fdf2e8a8c4fad9_poggit\libasynql\base\DataConnectorImpl->_390328fdf2e8a8c4fad9_poggit\libasynql\base\{closure}(array[1])
#9 plugins/CPlot_dev-development.phar/src/_390328fdf2e8a8c4fad9_poggit/libasynql/base/DataConnectorImpl(322): _390328fdf2e8a8c4fad9_poggit\libasynql\base\SqlThreadPool->readResults(array[6])
#10 plugins/CPlot_dev-development.phar/src/_390328fdf2e8a8c4fad9_poggit/libasynql/base/SqlThreadPool(64): _390328fdf2e8a8c4fad9_poggit\libasynql\base\DataConnectorImpl->checkResults()
#11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): _390328fdf2e8a8c4fad9_poggit\libasynql\base\SqlThreadPool->_390328fdf2e8a8c4fad9_poggit\libasynql\base\{closure}()
#12 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#14 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686651959.6802)
#15 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#16 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[12] /home/CCPM5/, string[20] /home/CCPM5/plugins/)
#17 pmsrc/src/PocketMine(357): pocketmine\server()
#18 pmsrc(11): require(string[56] phar:///home/CCPM5/PocketMine-MP.phar/src/PocketMine.php)

**Comment by note3crafter** [comment]
I tried again but now when I do /p generate it crashes again?! had removed the CPlot folder in plugin_data

However, if I want to use my world with the data, there is the aforementioned crash when the server starts

  #0 plugins/CPlot_dev-development.phar/src/_48e62591872a1dc7f793_SOFe/AwaitGenerator/Await(334): _48e62591872a1dc7f793_SOFe\AwaitGenerator\Await->reject(object JsonException#100216)
  #1 plugins/CPlot_dev-development.phar/src/_48e62591872a1dc7f793_SOFe/AwaitGenerator/Await(129): _48e62591872a1dc7f793_SOFe\AwaitGenerator\Await->wakeup(array[2])
  #2 plugins/CPlot_dev-development.phar/src/ColinHDev/CPlot/commands/AsyncSubcommand(13): _48e62591872a1dc7f793_SOFe\AwaitGenerator\Await::g2c(object Generator#100095)
  #3 plugins/CPlot_dev-development.phar/src/ColinHDev/CPlot/commands/PlotCommand(133): ColinHDev\CPlot\commands\AsyncSubcommand->execute(object pocketmine\player\Player#181610, array[1])
  #4 pmsrc/src/command/SimpleCommandMap(212): ColinHDev\CPlot\commands\PlotCommand->execute(object pocketmine\player\Player#181610, string[1] p, array[1])
  #5 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#181610, string[15] p generate TEST)
  #6 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#181610, string[15] p generate TEST)
  #7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(818): pocketmine\player\Player->chat(string[16] /p generate TEST)
  #8 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#99835)
  #9 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#137695)
  #10 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#99835, string[38] M./p generate TEST..A..#..k>..L..Z...D)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[42] S.../PHO.K-J,IU.q..aX..m....l.%.|^..Z.....)
  #12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[51] .ZK'..f...i*....h...U....n.@.I...+...5o.w._,.r..lMW)
  #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#168930)
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #15 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #17 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686657377.0896)
  #18 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #19 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[12] /home/CCPM5/, string[20] /home/CCPM5/plugins/)
  #20 pmsrc/src/PocketMine(357): pocketmine\server()
  #21 pmsrc(11): require(string[56] phar:///home/CCPM5/PocketMine-MP.phar/src/PocketMine.php)
--- Previous ---
JsonException: "Malformed UTF-8 characters, possibly incorrectly encoded" (5) in "plugins/CPlot_dev-development.phar/src/ColinHDev/CPlot/commands/subcommands/GenerateSubcommand" at line 41
  #0 plugins/CPlot_dev-development.phar/src/ColinHDev/CPlot/commands/subcommands/GenerateSubcommand(41): json_encode(array[15], int 4194304)
  #1 (): ColinHDev\CPlot\commands\subcommands\GenerateSubcommand->executeAsync(object pocketmine\player\Player#181610, array[1])
  #2 plugins/CPlot_dev-development.phar/src/_48e62591872a1dc7f793_SOFe/AwaitGenerator/Await(332): Generator->rewind()
  #3 plugins/CPlot_dev-development.phar/src/_48e62591872a1dc7f793_SOFe/AwaitGenerator/Await(129): _48e62591872a1dc7f793_SOFe\AwaitGenerator\Await->wakeup(array[2])
  #4 plugins/CPlot_dev-development.phar/src/ColinHDev/CPlot/commands/AsyncSubcommand(13): _48e62591872a1dc7f793_SOFe\AwaitGenerator\Await::g2c(object Generator#100095)
  #5 plugins/CPlot_dev-development.phar/src/ColinHDev/CPlot/commands/PlotCommand(133): ColinHDev\CPlot\commands\AsyncSubcommand->execute(object pocketmine\player\Player#181610, array[1])
  #6 pmsrc/src/command/SimpleCommandMap(212): ColinHDev\CPlot\commands\PlotCommand->execute(object pocketmine\player\Player#181610, string[1] p, array[1])
  #7 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#181610, string[15] p generate TEST)
  #8 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#181610, string[15] p generate TEST)
  #9 pmsrc/src/network/mcpe/handler/InGamePacketHandler(818): pocketmine\player\Player->chat(string[16] /p generate TEST)
  #10 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#99835)
  #11 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#137695)
  #12 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#99835, string[38] M./p generate TEST..A..#..k>..L..Z...D)
  #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[42] S.../PHO.K-J,IU.q..aX..m....l.%.|^..Z.....)
  #14 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[51] .ZK'..f...i*....h...U....n.@.I...+...5o.w._,.r..lMW)
  #15 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#168930)
  #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #17 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #19 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686657377.0896)
  #20 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #21 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[12] /home/CCPM5/, string[20] /home/CCPM5/plugins/)
  #22 pmsrc/src/PocketMine(357): pocketmine\server()
  #23 pmsrc(11): require(string[56] phar:///home/CCPM5/PocketMine-MP.phar/src/PocketMine.php)

**Comment by ColinHDev** [comment]
This should be fixed as of 85b2716fde538171718657423a8975c7c6f45a9b
