### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GamilinoMC** [ColinHDev/CPlot#80]
[CityBuild-1_2023-06-13_10_23_15.log](https://github.com/ColinHDev/CPlot/files/11733825/CityBuild-1_2023-06-13_10_23_15.log)

**Comment by GamilinoMC** [comment]
Exception Class: RuntimeException
Error: this pocketmine\scheduler\AsyncWorker is no longer running and cannot accept tasks
File: pmsrc/src/scheduler/AsyncPoolWorkerEntry
Line: 51
Plugin involved: none
Plugin: 
Code: 
[42] 		public readonly int $sleeperNotifierId
[43] 	){
[44] 		$this->lastUsed = time();
[45] 		$this->tasks = new \SplQueue();
[46] 	}
[47] 
[48] 	public function submit(AsyncTask $task) : void{
[49] 		$this->tasks->enqueue($task);
[50] 		$this->lastUsed = time();
[51] 		$this->worker->stack($task);
[52] 	}
[53] }

Trace: 
#0 pmsrc/src/scheduler/AsyncPoolWorkerEntry(51): pmmp\thread\Worker->stack(object pocketmine\network\mcpe\ChunkRequestTask#88296)
#1 pmsrc/src/scheduler/AsyncPool(152): pocketmine\scheduler\AsyncPoolWorkerEntry->submit(object pocketmine\network\mcpe\ChunkRequestTask#88296)
#2 pmsrc/src/scheduler/AsyncPool(198): pocketmine\scheduler\AsyncPool->submitTaskToWorker(object pocketmine\network\mcpe\ChunkRequestTask#88296, int 0)
#3 pmsrc/src/network/mcpe/cache/ChunkCache(128): pocketmine\scheduler\AsyncPool->submitTask(object pocketmine\network\mcpe\ChunkRequestTask#88296)
#4 pmsrc/src/network/mcpe/NetworkSession(1052): pocketmine\network\mcpe\cache\ChunkCache->request(int 0, int 8)
#5 pmsrc/src/player/Player(841): pocketmine\network\mcpe\NetworkSession->startUsingChunk(int 0, int 8, object Closure#93446)
#6 pmsrc/src/promise/Promise(45): pocketmine\player\Player->pocketmine\player\{closure}(object pocketmine\world\format\Chunk#88211)
#7 pmsrc/src/player/Player(845): pocketmine\promise\Promise->onCompletion(object Closure#93448, object Closure#88212)
#8 pmsrc/src/player/Player(1014): pocketmine\player\Player->requestChunks()
#9 pmsrc/src/network/mcpe/NetworkSession(1174): pocketmine\player\Player->doChunkRequests()
#10 pmsrc/src/network/NetworkSessionManager(90): pocketmine\network\mcpe\NetworkSession->tick()
#11 pmsrc/src/network/Network(92): pocketmine\network\NetworkSessionManager->tick()
#12 pmsrc/src/Server(1792): pocketmine\network\Network->tick()
#13 pmsrc/src/Server(1671): pocketmine\Server->tick()
#14 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#15 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[28] /home/Cloud/tmp/CityBuild-1/, string[36] /home/Cloud/tmp/CityBuild-1/plugins/)
#16 pmsrc/src/PocketMine(357): pocketmine\server()
#17 pmsrc(11): require(string[73] phar:///home/Cloud/storage/software/PocketMine-MP.phar/src/PocketMine.php)
Server Time: 13.06.2023 (Tuesday): 10:23:14 [UTC]
Server Uptime: 39.523133039474
Server Git Commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP Version: 8.1.19 (JIT disabled)

**Comment by ColinHDev** [comment]
This should be fixed as of 85b2716fde538171718657423a8975c7c6f45a9b

**Comment by ColinHDev** [comment]
I closed the wrong issue...
This was meant for #79

**Comment by ColinHDev** [comment]
Now it should be fixed as of 69dc49276ade7a4d99585c90e4147560dd9042a3
