### ISSUE TITLE
Crash when Loading CB Map whit data files from PM4

### ISSUE THREAD

**Issue by note3crafter** [ColinHDev/CPlot#81]
PocketMine-MP Crash Dump Tue Jun 13 18:21:51 UTC 2023

PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.2.6
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CPlot

Error: Unhandled async exception: zlib_decode(): data error
File: plugins/CPlot_dev-development (1).phar/src/_eb334591c4fd89760d72_SOFe/AwaitGenerator/Await
Line: 587
Type: _eb334591c4fd89760d72_SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 plugins/CPlot_dev-development (1).phar/src/_eb334591c4fd89760d72_SOFe/AwaitGenerator/Await(334): _eb334591c4fd89760d72_SOFe\AwaitGenerator\Await->reject(object ErrorException#59780)
#1 plugins/CPlot_dev-development (1).phar/src/_eb334591c4fd89760d72_SOFe/AwaitGenerator/Await(317): _eb334591c4fd89760d72_SOFe\AwaitGenerator\Await->wakeup(object Closure#186265)
#2 plugins/CPlot_dev-development (1).phar/src/_eb334591c4fd89760d72_SOFe/AwaitGenerator/Await(552): _eb334591c4fd89760d72_SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#186265)
#3 plugins/CPlot_dev-development (1).phar/src/_eb334591c4fd89760d72_SOFe/AwaitGenerator/AwaitChild(52): _eb334591c4fd89760d72_SOFe\AwaitGenerator\Await->recheckPromiseQueue(object _eb334591c4fd89760d72_SOFe\AwaitGenerator\AwaitChild#59711)
#4 plugins/CPlot_dev-development (1).phar/src/_03786ca77cbd870d889d_poggit/libasynql/base/DataConnectorImpl(197): _eb334591c4fd89760d72_SOFe\AwaitGenerator\AwaitChild->resolve(array[1])
#5 plugins/CPlot_dev-development (1).phar/src/_03786ca77cbd870d889d_poggit/libasynql/base/DataConnectorImpl(174): _03786ca77cbd870d889d_poggit\libasynql\base\DataConnectorImpl::_03786ca77cbd870d889d_poggit\libasynql\base\{closure}(array[1], array[14])
#6 plugins/CPlot_dev-development (1).phar/src/_03786ca77cbd870d889d_poggit/libasynql/base/DataConnectorImpl(181): _03786ca77cbd870d889d_poggit\libasynql\base\DataConnectorImpl::_03786ca77cbd870d889d_poggit\libasynql\base\{closure}(object _03786ca77cbd870d889d_poggit\libasynql\result\SqlSelectResult#185880)
#7 plugins/CPlot_dev-development (1).phar/src/_03786ca77cbd870d889d_poggit/libasynql/base/DataConnectorImpl(239): _03786ca77cbd870d889d_poggit\libasynql\base\DataConnectorImpl::_03786ca77cbd870d889d_poggit\libasynql\base\{closure}(array[1])
#8 plugins/CPlot_dev-development (1).phar/src/_03786ca77cbd870d889d_poggit/libasynql/base/SqlThreadPool(111): _03786ca77cbd870d889d_poggit\libasynql\base\DataConnectorImpl->_03786ca77cbd870d889d_poggit\libasynql\base\{closure}(array[1])
#9 plugins/CPlot_dev-development (1).phar/src/_03786ca77cbd870d889d_poggit/libasynql/base/DataConnectorImpl(322): _03786ca77cbd870d889d_poggit\libasynql\base\SqlThreadPool->readResults(array[7])
#10 plugins/CPlot_dev-development (1).phar/src/_03786ca77cbd870d889d_poggit/libasynql/base/SqlThreadPool(64): _03786ca77cbd870d889d_poggit\libasynql\base\DataConnectorImpl->checkResults()
#11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): _03786ca77cbd870d889d_poggit\libasynql\base\SqlThreadPool->_03786ca77cbd870d889d_poggit\libasynql\base\{closure}()
#12 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#14 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686680511.4678)
#15 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#16 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[12] /home/CCPM5/, string[20] /home/CCPM5/plugins/)
#17 pmsrc/src/PocketMine(357): pocketmine\server()
#18 pmsrc(11): require(string[56] phar:///home/CCPM5/PocketMine-MP.phar/src/PocketMine.php)

Code:
[578] 		$this->sleeping = true;
[579] 
[580] 		parent::reject($throwable);
[581] 		foreach($this->catches as $class => $onError){
[582] 			if($class === "" || is_a($throwable, $class)){
[583] 				$onError($throwable);
[584] 				return;
[585] 			}
[586] 		}
[587] 		throw new AwaitException("Unhandled async exception: {$throwable->getMessage()}", 0, $throwable);
[588] 	}
[589] 
[590] 	/**
[591] 	 * @internal This is implementation detail. Existence, signature and behaviour are semver-exempt.
[592] 	 */
[593] 	public function isSleeping() : bool{
[594] 		return $this->sleeping;
[595] 	}
[596] }

Loaded plugins:
CPlot development by ColinHDev for API(s) 5.0.0
CoreV7 7.1.1_BETA by TheNote/Rudolf2000/note3crafter, TheNote/Rudolf2000, tim03we, xxflow, Aneoxic, FleekRush, JackMD, LookItsAku, Philip, Hagnbrain, EnderDirt, Crasher508, MDevPmmP, jojoe77777, GamerMJay for API(s) 5.0.0
DevTools 1.17.0 by PocketMine Team for API(s) 5.0.0
EasyEdit 3.0.0 by platz1de for API(s) 5.0.0
MultiWorld 2.1.0-beta2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 5.0.0
MysteryCrate 11.0.0 by JackMD, DaPigGuy, Crasher508, TheNote for API(s) 5.0.0
RegisterBlockDemoPM5 0.0.1 by  for API(s) 5.0.0
Secrets 1.0.0 by Crasher508 for API(s) 5.0.0
Slapper 3.0.0 by Vecnavium, jojoe77777 for API(s) 5.0.0
SlapperRotationV2 2.0.5 by xqwtxon for API(s) 5.0.0
Texter 4.2.0 by yuko fuyutsuki, mfmfnek0, onebone, ogiwara, Shootsta_ERU0531, Toganon, ShadowArt, Marron0421, No4NaMe, iteplenky, SuperYYT, SuperAdam47, minijaham, VicoSilalahi, TobyDev265, IvanCraft623 for API(s) 5.1.2
TopVoter 4.0.0 by SalmonDE, TheNote\RetroRolf for API(s) 5.0.0

uname -a: Linux v2202209184155202463 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64
Zend version: 4.2.6
Composer libraries: 
- adhocore/json-comment 1.2.1@651023f9fe52e9efa2198cbaf6e481d1968e2377
- brick/math 0.11.0@0ad82ce168c82ba30d1c01ec86116ab52f589478
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.5.0@42060ed45344789fb9f21f9f1864fc47b9e3507b
- netresearch/jsonmapper unknown@unknown
- pocketmine/bedrock-block-upgrade-schema 2.2.0@79bb3ad542ef19e828fdf1fa6adc54f1fa4b3bb5
- pocketmine/bedrock-data 2.3.0+bedrock-1.20.0@b3dd3f4b8e3b6759c5d84de6ec85bb20b668c3a9
- pocketmine/bedrock-item-upgrade-schema 1.3.0@b16c59cfae08833f180dd82f88de7c1f43bc67c9
- pocketmine/bedrock-protocol 22.0.0+bedrock-1.20.0@ceff28a0bd5d248f37fb97be3e836d536e37526e
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/color 0.3.1@a0421f1e9e0b0c619300fb92d593283378f6a5e1
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.19.5@71af5f9bd23b4e4bad8920dac7f4fe08e5205f7d
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/math 0.4.3@47a243d320b01c8099d65309967934c188111549
- pocketmine/nbt 0.3.4@62c02464c6708b2467c1e1a2af01af09d5114eda
- pocketmine/netresearch-jsonmapper v4.2.999@f700806dec756ed825a8200dc2950ead98265956
- pocketmine/pocketmine-mp 5.1.2@7cd317bf398a017f7c690a475c5a67650c610323
- pocketmine/raklib 0.15.1@79b7b4d1d7516dc6e322514453645ad9452b20ca
- pocketmine/raklib-ipc 0.2.0@26ed56fa9db06e4ca6e8920c0ede2e01e219bb9c
- pocketmine/snooze 0.5.0@a86d9ee60ce44755d166d3c7ba4b8b8be8360915
- ramsey/collection 2.0.0@a4b48764bfbb8f3a6a4d1aeb1a35bb5e9ecac4a5
- ramsey/uuid 4.7.4@60a4c63ab724854332900504274f6150ff26d286
- rhumsaa/uuid unknown@unknown
- symfony/filesystem v6.2.10@fd588debf7d1bc16a2c84b4b3b71145d9946b894
- symfony/polyfill-ctype v1.27.0@5bbc823adecdae860bb64756d639ecfec17b050a
- symfony/polyfill-mbstring v1.27.0@8ad114f6b39e2c98a8b0e3bd907732c207c2b534

**Comment by note3crafter** [comment]
This error happens when you try to load your PM4 CPlot world on a PM5 server with the associated data!

**Comment by ColinHDev** [comment]
Fixed as of fca502687044369cc368c9ab43156324f7bfc7cb
