### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by UnknownNull** [ColinHDev/CPlot#86]
Can the data and world related to MyPlot plugin be transferred to CPlot and continue the previous process without any problems?

**Comment by ColinHDev** [comment]
Yes, it should work. Just replace the `MyPlot.phar` with the `CPlot.phar` and load your plot world after restarting your server. Then everything should be automatically converted.

**Comment by UnknownNull** [comment]
The .db format of the myplot plugin was not recognized to convert to a new database and could only recognize the world

**Comment by ColinHDev** [comment]
Please create a separate issue if you encounter any bugs
