### ISSUE TITLE
EconomyAPI support

### ISSUE THREAD

**Issue by iTzAndrew33212** [ColinHDev/CPlot#87]
Hi there

Curious if it would be possible to add EconomyAPI-PM5 as a economy support please

EconomyAPI-PM5 by mathchat900

Take care
Andrew

**Comment by supercrafter333** [comment]
EconomyAPI is not performant and it's also officially end-of-life (EOL).

**Comment by ColinHDev** [comment]
Yes, so officially EconomyAPI is dead and initially, when writing the economy providers, I didn't want to encourage players to keep using it by providing support for it.
But I don't think that anyone who hasn't switched till now, will ever. So, I don't see, why it couldn't be supported in CPlot, if there is really that much demand for it.

But still: @supercrafter333 is definitely right. There are better alternatives and you should no longer use EconomyAPI.

**Comment by iTzAndrew33212** [comment]
What about EconomyAPI-PM5 made by mathchat900 commands are working completely fine, everything is compatible, bedrockeconomy is having issues with its commands atm, which is why im doing the switch.

**Comment by iTzAndrew33212** [comment]
> What about EconomyAPI-PM5 made by mathchat900 commands are working completely fine, everything is compatible, bedrockeconomy is having issues with its commands atm, which is why im doing the switch.

The plugin is fairly new....

**Comment by ColinHDev** [comment]
It's not about the repository being new. 
There is a reason why everybody is encouraging everyone to switch to BedrockEconomy or Capital since the release of PM4. It's about the plugin being not well-made and performing worse and worse the more player data it has to work with and it tearing the server's ability to function properly down along with it.

**Comment by iTzAndrew33212** [comment]
> It's not about the repository being new. There is a reason why everybody is encouraging everyone to switch to BedrockEconomy or Capital since the release of PM4. It's about the plugin being not well-made and performing worse and worse the more player data it has to work with and it tearing the server's ability to function properly down along with it.

Thats totally understandable, thank you for getting back and explaining tho, appreciate it 🔥

Take care
Andrew
