### ISSUE TITLE
Update Blocks after plot reset

### ISSUE THREAD

**Issue by GamerMJay** [ColinHDev/CPlot#98]
Hi, I merged my plot and then did /p reset and then these update blocks were there.

![Bild_2023-09-22_152036086](https://github.com/ColinHDev/CPlot/assets/66413999/7bce81bc-1460-41f1-a0be-c1f7b8f2b1b0)

**Comment by GamerMJay** [comment]
i use the latest CPlot version (#208)

**Comment by ColinHDev** [comment]
Is this still happening?

**Comment by GamerMJay** [comment]
No, I created a new plot world

**Comment by GamerMJay** [comment]
I went a bit out of the plot world and suddenly see that the generation is with update blocks.
![image](https://github.com/ColinHDev/CPlot/assets/66413999/d1c0475f-4805-4744-9066-c6e411f1fefa)
